config/routes.rb
Rails.application.routes.draw do
  
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resources :activates, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, only: [:edit, :update, :show, :destroy], param: :name do
    member do
      get :unsubscribed
    end
  end
  resources :users, only: [:index] do
    resource :follows, only: [:create, :destroy]
    member do
      get :activate, param: :activation_token
    end
  end
  resources :tweets, only: [:index, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end 
  
  get 'login' => 'sessions#new'
  post 'logout' => 'sessions#destroy'
  root to: 'registrations#new' 
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :require_login, raise: false

  def create
    @user = User.find_by_email(params[:email])
    @user.deliver_reset_password_instructions! if @user
    redirect_to(root_path, :notice => 'パスワード更新用メールを送信しました')
  end

  def edit
    set_token_user_from_params?
  end

  def update
    return if !set_token_user_from_params?

    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'パスワードの更新に成功しました')
    else
      render :edit
    end
  end

  private

    def set_token_user_from_params?
      @token = params[:id]
      @user = User.load_from_reset_password_token(params[:id])

      if @user.blank?
        not_authenticated
        return false
      else
        return true
      end
    end
end

app/helpers/password_resets.rb
module PasswordResetsHelper
  def require_login
    unless logged_in?
      flash[:error] = "ログインしてください"
      redirect_to "/sessions/new"
    end
  end
    
  def logged_in?
    !current_user.nil?
  end
end

app/views/password_resets/edit.html.slim
- provide(:title, "パスワードリセット")
.l-left-space
.l-center-space
  .form.t-form
    = form_with model: @user, url: password_reset_path(@token), method: :put do |f|
      - if errors = @user.errors.full_messages_for(:display_name)
        - errors.each do |error|
          .message
            = error
      h2.form-title
        | パスワードリセット
      = f.label :email
      = @user.email
      .input-field
        = f.label :password, "新規パスワード(6~24文字)"
        = f.password_field :password, id: 'password', type: "password", required: 'true', minlength: '6', maxlength: '24'
      .input-field
        = f.label :password_confirmation, "確認用パスワード"
        = f.password_field :password_confirmation, id: 'password_confirmation', type: "password", required: 'true', minlength: '6', maxlength: '24'
      = f.submit "パスワードを変更する", class: "button"
.l-right-space

app/views/password_resets/new.html.slim
- provide(:title, "パスワードリセット")
.l-left-space
.l-center-space
  .form.t-form
    = form_with model: @user, url: password_resets_path, method: :post do |f|
      h2.form-title
          | パスワードリセット
      .input-field
        = f.label :email, "メールアドレス"
        = f.text_field :email, id: 'email', type: "email", required: 'true'
      = f.submit "パスワード変更メールを送信する", class: "button"
.l-right-space