config/routes.rb
Rails.application.routes.draw do
  
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resources :activates, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, only: [:edit, :update, :show, :destroy], param: :name do
    member do
      get :unsubscribed
    end
  end
  resources :users, only: [:index] do
    resource :follows, only: [:create, :destroy]
    member do
      get :activate, param: :activation_token
    end
  end
  resources :tweets, only: [:index, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end 
  
  get 'login' => 'sessions#new'
  post 'logout' => 'sessions#destroy'
  root to: 'registrations#new' 
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    mount_uploaders :images, ImageUploader
    serialize :images, JSON
    belongs_to :user
    has_many :favorites, dependent: :destroy
  
    validates :user, presence: true
    validates :content, presence: true, length: { in: 1..140}
    
    def favorited_by? user
        favorites.where(user_id: user.id).exists?
    end 
   
    default_scope -> { order(created_at: :desc) } 
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_login

  def index
    @search = Tweet.ransack(params[:q])
    @tweets = @search.result
    @search2 = current_user.inverse_followers.ransack(params[:p])
    @users = @search2.result
    @tweet  = Tweet.new
    @user = User.find_by(name: current_user.name)
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    if @tweet.save
      redirect_to tweets_url
    else
      redirect_to tweets_url
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.json { head :no_content }
    end
  end

  private
    def tweet_params
      params.require(:tweet).permit(:content, {images: []}) 
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/index.html.slim
.l-sub-space
  .tweet-form
    .user-description-sapce-t
      .t-text
        = link_to user_path(current_user)
          = current_user.display_name
    .t-text-unemphasized
      = "@" + current_user.name
    .user-activity-space-t.border-bottom.t-border
      .num-space-t
        .t-text-unemphasized
          |tweet
        .t-num
          a href="/users/#{current_user.name}#tab1"
            = current_user.tweets.count
      .num-space-t
        .t-text-unemphasized
          |フォロー
        .t-num
          a href="/users/#{current_user.name}#tab2" 
            = current_user.follows.count
      .num-space-t
        .t-text-unemphasized
          |フォロワー
        .t-num
          a href="/users/#{current_user.name}#tab3"
            = current_user.followers.count
      .num-space-t
        .t-text-unemphasized
          |お気に入り
        .t-num
          a href="/users/#{current_user.name}#tab4"
            = current_user.favorites.count
    = form_with model: @tweet do |f|
      .input-field
        = f.text_area :content, required: 'true', maxlength: '140', class: 'js-text'
      p style="text-align:right;" class="js-text-count"
      = f.file_field :images, class: "dropify", multiple: true
      = f.file_field :images, class: "dropify", multiple: true
      = f.file_field :images, class: "dropify", multiple: true
      = f.file_field :images, class: "dropify", multiple: true
      = f.submit "つぶやく", class: "button"
.l-main-space
  .main-content-field
    .main-content-title-space
      .main-content-title
        .tab-wrap
          .tab-label.select.tab-l id="tab1" 全体投稿
          .tab-label.tab-r id="tab2" フォロー
          .search_wap.select#tab1
            = search_form_for @search, url: tweets_path do |f|
              = f.text_field :content_cont , placeholder: "ツイートを検索"
                = button_tag "", :name => nil, class: "search__button"
                  .icon_wap
                    i.material-icons search
          .search_wap#tab2
            = search_form_for @search2, as: :p, url: tweets_path do |f|
              = f.text_field :tweets_content_cont , placeholder: "ツイートを検索"
                = button_tag "", :name => nil, class: "search__button"
                  .icon_wap
                    i.material-icons search
          .tab-content.select#tab1
            - if @tweets.empty?
              | Tweetはありません
            - else
              - @tweets.each do |t|
                .block
                  .icon-space
                    - if t.user.icon.present?
                      = link_to user_path(t.user.name)
                        = image_tag t.user.icon.url
                    - else
                      = link_to user_path(t.user.name)
                        = image_tag asset_path("icon.jpg")
                  .main-space
                    .top-space
                      .name-space
                        .t-text.inline
                          = link_to user_path(t.user.name)
                            = t.user.display_name
                        .t-text-unemphasized
                          = "@" + t.user.name
                          | ・
                          = distance_of_time_in_words_to_now(t.created_at)
                      .follow-buttun-space
                        - if t.user == current_user
                          |
                        - elsif t.user.followed_by? current_user
                          = button_to "フォロー解除", user_follows_path(t.user), method: :delete, data: {confirm: "フォローを解除しますか？"}, class: "following-button"
                        - else
                          = button_to "フォロー", user_follows_path(t.user), method: :post, class: " follow-button"
                    .bottom-space
                      .content-text
                        = t.content
                    .image-space
                      - t.images.each do |image|
                        =  link_to image.url, 'data-lightbox': image do
                          = image_tag(image.url, class: "image1") if t.images?
                    .option-space
                      .favotite-space
                        - if t.favorited_by? current_user
                          = link_to "favorite", tweet_favorites_path(t), method: :delete, class: "material-icons"
                        - else
                          = link_to "favorite_border", tweet_favorites_path(t), method: :post, class: "material-icons"
                      .delete-space
                        - if t.user_id == current_user.id
                          = link_to "delete", tweet_path(t), method: :delete, data: {confirm: "ツイートを削除しますか？"}, class: "material-icons"
                        - else
                          |
          .tab-content#tab2
            - if current_user.inverse_followers.empty?
              | フォロー中の方のTweetはありません
            - else
              - @users.each do |f|
                - f.tweets.each do |t|
                  .block
                    .icon-space
                      - if f.icon.present?
                        = link_to user_path(f.name)
                          = image_tag f.icon.url
                      - else
                        = link_to user_path(f.name)
                          = image_tag asset_path("icon.jpg")
                    .main-space  
                      .top-space
                        .name-space
                          .t-text.inline
                            = link_to user_path(f.name)
                              = f.display_name
                          .t-text-unemphasized
                            = "@" + f.name
                            | ・
                            = distance_of_time_in_words_to_now(t.created_at)
                        .follow-buttun-space
                          - if f.followed_by? current_user
                            = button_to "フォロー解除", user_follows_path(f), method: :delete, data: {confirm: "フォローを解除しますか？"}, class: "following-button"
                          - else
                            = button_to "フォロー", user_follows_path(f), method: :post, class: "follow-button"
                      .bottom-space
                        .content-text
                          = t.content
                      .image-space
                        - t.images.each do |image|
                          = link_to image.url, 'data-lightbox': image do
                            = image_tag(image.url, class: "image1")
                      .option-space
                        .favotite-space
                          - if t.favorited_by? current_user
                            = link_to "favorite", tweet_favorites_path(t), method: :delete, class: "material-icons"
                          - else
                            = link_to "favorite_border", tweet_favorites_path(t), method: :post, class: "material-icons"
                        .delete-space
                          - if t.user_id == current_user.id
                            = link_to "delete", tweet_path(t), method: :delete, data: {confirm: "ツイートを削除しますか？"}, class: "material-icons"
                          - else
                            |

= javascript_include_tag 'dropify'
javascript:
	$(document).ready(function(){
		$('.dropify').dropify();
	});

= javascript_include_tag 'count'
= javascript_include_tag 'tab'
= javascript_include_tag 'image'