config/routes.rb
Rails.application.routes.draw do
  
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resources :activates, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, only: [:edit, :update, :show, :destroy], param: :name do
    member do
      get :unsubscribed
    end
  end
  resources :users, only: [:index] do
    resource :follows, only: [:create, :destroy]
    member do
      get :activate, param: :activation_token
    end
  end
  resources :tweets, only: [:index, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end 
  
  get 'login' => 'sessions#new'
  post 'logout' => 'sessions#destroy'
  root to: 'registrations#new' 
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  
  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :follows, foreign_key: :follower_id, dependent: :destroy
  has_many :inverse_followers, through: :follows, dependent: :destroy
  has_many :inverse_follows, foreign_key: :inverse_follower_id, dependent: :destroy, class_name: "Follow"
  has_many :followers, through: :inverse_follows, dependent: :destroy
  
  mount_uploader :icon, IconUploader
  serialize :icon, JSON
  
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[a-z][a-z0-9]+\z/ }, length: { in: 4..24 }
  validates :display_name, presence: true, length: { in: 1..15 }
  validates :bio, length: { maximum: 140  }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, confirmation: true, length: { in: 6..24 }, if: :password
  validates :password_confirmation, presence: true, if: :password
  
  def followed_by? user
    inverse_follows.where(follower_id: user.id).exists?
  end
  
  def favorited_by? user
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, :only => [:activate]

  # GET /users
  # GET /users.json
  def index
    @search = User.ransack(params[:q])
    @users = @search.result
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by(name: params[:name])
    @search = User.find_by(name: params[:name]).tweets.ransack(params[:q])
    @tweets = @search.result
    @search2 = User.find_by(name: params[:name]).inverse_followers.ransack(params[:q2])
    @inverse_followers = @search2.result
    @search3 = User.find_by(name: params[:name]).followers.ransack(params[:q3])
    @followers = @search3.result
    @search4 = User.find_by(name: params[:name]).favorites.ransack(params[:q4])
    @favorites = @search4.result.order(created_at: "DESC")
  end

  # GET /users/1/edit
  def edit
    @user = User.find_by(name: params[:name])
      unless @user = current_user
        redirect_to @user
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = current_user
    if @user.update_attributes(params_user)
      redirect_to user_path(@user.name)
    else
      render :edit
    end 
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find_by(name: params[:name])
    @user.destroy
    redirect_to root_path, notice: '退会が完了いたしました。本サービスをご利用いただき誠にありがとうございました。'
  end
  
  def unsubscribed
    @user = User.find_by(name: params[:name])
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      redirect_to(login_path, :notice => 'ユーザー認証に成功しました')
    else
      not_authenticated
    end
  end
  
  private
    def params_user
      params.require(:user).permit(:name, :display_name, :bio, :icon)
    end
    
    def require_login
      unless logged_in?
        flash[:error] = "ログインしてください"
        redirect_to "/sessions/new"
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/edit.html.slim
- provide(:title, "ユーザー編集")
.l-left-space
.l-center-space
  .form.t-form
    = form_with model: @user, url: user_path(params[:name]), method: :patch, local: true do |f|
      h2.form-title
        | プロフィール編集
      .input-icon
        - if current_user.icon.present?
          = image_tag current_user.icon.url, id: :icon_preview, onClick:"$('#icon').click()"
        - else
          = image_tag asset_path("icon.jpg"), id: :icon_preview, onClick:"$('#icon').click()"
        = f.file_field :icon, id: :icon
      .input-field
        = f.label :name, "ユーザーID(4~24文字)"
        = f.text_field :name, required: 'true', minlength: '4', maxlength: '24', pattern: '^[a-z][a-z0-9]+'
      - if errors = @user.errors.full_messages_for(:name)
        - errors.each do |error|
          .message
            = error
      .input-field
        = f.label :display_name, "ユーザー名(1~15文字)"
        = f.text_field :display_name, required: 'true', minlength: '1', maxlength: '15'
      - if errors = @user.errors.full_messages_for(:display_name)
        - errors.each do |error|
          .message
            = error
      .input-field
        = f.label :bio, "プロフィール(140文字)"
        = f.text_area :bio, class: "js-text", maxlength: '140'
      p style="text-align:right;" class="js-text-count"
      - if errors = @user.errors.full_messages_for(:bio)
        - errors.each do |error|
          .message
            = error
      
          = f.file_field :icon
      = f.submit "送信する", class: "button"
.l-right-space

= javascript_include_tag 'icon'
= javascript_include_tag 'count'

app/views/users/index.html.slim
- provide(:title, "ユーザー一覧")
.l-left-space
.l-center-space
  .main-content-field
    .main-content-title-space
      .main-content-title
        .tab-wrap
          .tab-label.select ユーザー一覧
          .search_wap.select#tab1
            = search_form_for @search, url: users_path do |f|
              = f.text_field :display_name_or_name_or_bio_cont , placeholder: "ユーザーを検索"
                = button_tag "", :name => nil, class: "search__button"
                  .icon_wap
                    i.material-icons search
          .tab-content.select
            - @users.each do |user|
              .block
                .icon-space
                  - if user.icon.present?
                    = link_to user_path(user.name)
                      = image_tag user.icon.url
                  - else
                    = link_to user_path(user.name)
                      = image_tag asset_path("icon.jpg")
                .main-space
                  .top-space
                    .name-space
                      .t-text
                        = link_to user_path(user.name)
                          = user.display_name
                      .t-text-unemphasized
                        = "@" +user.name
                    .follow-buttun-space
                      - if current_user.id == user.id
                        |
                      - elsif user.followed_by? current_user
                        = button_to "フォロー解除", user_follows_path(user), method: :delete, data: {confirm: "フォローを解除しますか？"}, class: "following-button"
                      - else
                        = button_to "フォロー", user_follows_path(user), method: :post, class: "follow-button"
                  .bottom-space
                    .content-text
                      = user.bio
.l-right-space
    

app/views/users/show.html.slim
- provide(:title, "マイページ")
.l-left-space
.l-center-space
  .user-space-column.t-block.border.t-border
    .user-space-row
      .user-icon-space
        - if @user.icon.present?
          = image_tag @user.icon.url
        - else
          = image_tag "icon.jpg"
      .user-main-space
        .user-top-space
          .user-name-space
            .t-text
              = @user.display_name
            .t-text-unemphasized
              = "@" + @user.name
          .user-buttun-space
            - if current_user.name == @user.name
              = button_to "プロフィール編集", edit_user_path(@user.name), method: :get, class: "follow-button"
            - elsif @user.followed_by? current_user
              = button_to "フォロー解除", user_follows_path(@user), method: :delete, data: {confirm: "フォローを解除しますか？"}, class: "following-button"
            - else
              = button_to "フォロー", user_follows_path(@user), method: :post, class: "follow-button" 
        .user-bottom-space
          .content-text
            = @user.bio
    .user-activity-space
      .user-num-space
        .t-text-unemphasized
          |tweet
        .t-num
          a href="/users/#{@user.name}#tab1"
            = @user.tweets.count
      .user-num-space
        .t-text-unemphasized
          |フォロー
        .t-num
          a href="/users/#{@user.name}#tab2" 
            = @user.follows.count
      .user-num-space
        .t-text-unemphasized
          |フォロワー
        .t-num
          a href="/users/#{@user.name}#tab3"
            = @user.followers.count
      .user-num-space
        .t-text-unemphasized
          |お気に入り
        .t-num
          a href="/users/#{@user.name}#tab4"
            = @user.favorites.count
  .main-content-field
    .main-content-title-space
      .tab-wrap
        .tab-label.select.tab-l id="tab1" Tweet
        .tab-label id="tab2" フォロー
        .tab-label id="tab3" フォロワー
        .tab-label.tab-r id="tab4" お気に入り
        .search_wap.select#tab1
            = search_form_for @search, url: user_path(@user.name) do |f|
              = f.text_field :content_cont , placeholder: "ツイートを検索"
                = button_tag "", :name => nil, class: "search__button"
                  .icon_wap
                    i.material-icons search
        .search_wap#tab2
            = search_form_for @search2, as: :q2, url: user_path(@user.name) do |f|
              = f.text_field :display_name_or_name_or_bio_cont, placeholder: "フォローを検索"
                = button_tag "", :name => nil, class: "search__button"
                  .icon_wap
                    i.material-icons search
        .search_wap#tab3
            = search_form_for @search3, as: :q3, url: user_path(@user.name) do |f|
              = f.text_field :display_name_or_name_or_bio_cont, placeholder: "フォロワーを検索"
                = button_tag "", :name => nil, class: "search__button"
                  .icon_wap
                    i.material-icons search
        .search_wap#tab4
            = search_form_for @search4, as: :q4, url: user_path(@user.name) do |f|
              = f.text_field :tweet_content_cont , placeholder: "お気に入りを検索"
                = button_tag "", :name => nil, class: "search__button"
                  .icon_wap
                    i.material-icons search
        .tab-content.select#tab1
          - if current_user.tweets.empty?
            | tweetしてみましょう
          - else
            - @tweets.each do |t|
              .block
                .icon-space
                  - if current_user.icon.present?
                    = link_to user_path(t.user.name)
                      = image_tag @user.icon.url
                  - else
                    = link_to user_path(t.user.name)
                      = image_tag asset_path("icon.jpg")
                .main-space
                  .top-space
                    .name-space
                      .t-text
                        = @user.display_name
                      .t-text-unemphasized
                        = "@" + @user.name
                        | ・
                        = distance_of_time_in_words_to_now(t.created_at)
                    .follow-buttun-space
                      - if @user == current_user
                        |
                      - elsif @user.followed_by? current_user
                        = button_to "フォロー解除", user_follows_path(@user), method: :delete, data: {confirm: "フォローを解除しますか？"}, class: "following-button"
                      - else
                        = button_to "フォロー", user_follows_path(@user), method: :post, class: "follow-button"
                  .bottom-space
                    .content-text
                      = t.content
                  .image-space
                    - t.images.each do |image|
                      = link_to image.url, 'data-lightbox': image do
                        = image_tag(image.url, class: "image1") if t.images?
                  .option-space
                    .favotite-space
                      - if t.favorited_by? current_user
                        = link_to "favorite", tweet_favorites_path(t), method: :delete,class: "material-icons"
                      - else
                        = link_to "favorite_border", tweet_favorites_path(t), method: :post, class: "material-icons"
                    .delete-space
                      - if t.user_id == current_user.id
                        = link_to "delete", tweet_path(t), method: :delete, data: {confirm: "ツイートを削除しますか？"}, class: "material-icons"
                      - else
                        |
        .tab-content#tab2
          - if @user.inverse_followers.empty?
            | フォローしてみましょう
          - else
            - @inverse_followers.each do |f|
              .block
                .icon-space
                  - if f.icon.present?
                    = link_to user_path(f.name)
                      = image_tag f.icon.url
                  - else
                    = link_to user_path(f.name)
                      = image_tag asset_path("icon.jpg")
                .main-space
                  .top-space
                    .name-space
                      .t-text
                        = link_to f.display_name, user_path(f.name)
                      .t-text-unemphasized
                        = "@" + f.name
                    .follow-buttun-space
                      - if f == current_user
                        |
                      - elsif f.followed_by? current_user
                        = button_to "フォロー解除", user_follows_path(f), method: :delete, data: {confirm: "フォローを解除しますか？"}, class: "following-button"
                      - else
                        = button_to "フォロー", user_follows_path(f), method: :post, class: "follow-button"
                  .bottom-space
                    .content-text
                      = f.bio
        .tab-content#tab3
          - if @user.followers.empty?
            | まだフォロワーがいません
          - else
            - @followers.each do |f|
              .block
                .icon-space
                  - if f.icon.present?
                    = link_to user_path(f.name)
                      = image_tag f.icon.url
                  - else
                    = link_to user_path(f.name)
                      = image_tag asset_path("icon.jpg")
                .main-space
                  .top-space
                    .name-space
                      .t-text
                        = link_to f.display_name, user_path(f.name)
                      .t-text-unemphasized
                        = "@" + f.name
                    .follow-buttun-space
                      - if f == current_user
                        |
                      - elsif f.followed_by? current_user
                        = button_to "フォロー解除", user_follows_path(f), method: :delete, data: {confirm: "フォローを解除しますか？"}, class: "following-button"
                      - else
                        = button_to "フォロー", user_follows_path(f), method: :post, class: "follow-button"
                  .bottom-space
                    .content-text
                      = f.bio
        .tab-content#tab4
          - if @user.favorites.empty?
            | まだお気に入りに登録されたツイートはありません
          - else
            - @favorites.each do |f|
              - user = User.find_by(id: f.tweet.user_id)
              .block
                .icon-space
                  - if user.icon.present?
                    = link_to user_path(user.name)
                      = image_tag user.icon.url
                  - else
                    = link_to user_path(user.name)
                      = image_tag asset_path("icon.jpg")
                .main-space
                  .top-space
                    .name-space
                      .t-text
                        = link_to user.display_name, user_path(user.name)
                      .t-text-unemphasized
                        = "@" + user.name
                        | ・
                        = distance_of_time_in_words_to_now(f.tweet.created_at)
                    .follow-buttun-space
                      - if user == current_user
                        |
                      - elsif user.followed_by?  current_user
                        = button_to "フォロー解除", user_follows_path(user), method: :delete, data: {confirm: "フォローを解除しますか？"}, class: "following-button"
                      - else
                        = button_to "フォロー", user_follows_path(user), method: :post, class: "follow-button"
                  .bottom-space
                    .content-text
                      = f.tweet.content
                  .image-space
                    - f.tweet.images.each do |image|
                      =  link_to image.url, 'data-lightbox': image do
                        = image_tag(image.url, class: "image1") if f.tweet.images?
                  .option-space
                    .favotite-space    
                      - if f.tweet.favorited_by? current_user
                        = link_to "favorite", tweet_favorites_path(f.tweet), method: :delete,class: "material-icons"
                      - else
                        = link_to "favorite_border", tweet_favorites_path(f.tweet), method: :post, class: "material-icons"
                    .delete-space
                      - if f.tweet.user_id == current_user.id
                        = link_to "delete", tweet_path(f.tweet), method: :delete, data: {confirm: "ツイートを削除しますか？"}, class: "material-icons"
                      - else
                        |
.l-right-space

= javascript_include_tag 'tab2'
= javascript_include_tag 'image'

app/views/users/unsubscribed.html.slim
- provide(:title, "退会")
.l-center-space
  .guides
    h2.guides-title
      = current_user.name
      |様の退会手続き
    .guides-explanation
      .guides-explanation-title
        h2
          strong
            |最終確認
      .guides-explanation-text
          h3
            |下記の
            strong
              |「退会する」
            |のボタンを押すと
            |最終確認のポップアップが表示されます。<br>
            |ポップアップのOKを押すと退会手続きは完了され、以降
            strong
              |ユーザーの復元は出来かねます
            |のでご注意ください。
    .unsubscribed
      = button_to '退会する', user_path, method: :delete, data: {confirm: "一度退会をするとユーザーの復元は行なえません。本当に退会なさいますか？"}, class: "button"