config/routes.rb
Rails.application.routes.draw do
  
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resources :activates, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, only: [:edit, :update, :show, :destroy], param: :name do
    member do
      get :unsubscribed
    end
  end
  resources :users, only: [:index] do
    resource :follows, only: [:create, :destroy]
    member do
      get :activate, param: :activation_token
    end
  end
  resources :tweets, only: [:index, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end 
  
  get 'login' => 'sessions#new'
  post 'logout' => 'sessions#destroy'
  root to: 'registrations#new' 
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/views/shared/_header.html.slim
.l-header
  nav
    .nav-wrapper
      a.brand-logo  TweetApp(仮)
      ul#nav-mobile.right.hide-on-med-and-down
        - if current_user
          li
            = link_to "ユーザー一覧", users_path, method: :get
          li
            = link_to "ホーム", tweets_path, method: :get
          li
            = link_to "マイページ" , user_path(current_user.name), method: :get
          li
            = link_to "ガイド", page_path('guides')
          li
            = link_to "ログアウト", sessions_path, method: :delete, data: {confirm: "ログアウトしますか？"}
        - else
          li
            = link_to "トップ", new_registrations_path, method: :get
          li
            = link_to "ガイド", page_path('guides')
          li
            = link_to "ログイン", new_sessions_path, method: :get

app/views/shared/_ransack.html.slim
.search_wap
  = search_form_for @search, url: tweets_path do |f|
    = f.text_field :content_cont , placeholder: "ツイートを検索"
    = button_tag "", :name => nil, class: "search__button"
      .icon_wap
        i.material-icons search